name: 'Push'

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ vars.wfvar }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

jobs:
  env-and-sleep:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.sha }}-${{ github.job }}-${{ vars.esjobvar }}
    steps:
      - run: |
        env
        sleep 1m

  hello-and-sleep:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ vars.hsjobvar }}
    steps:
      - run: |
        echo 'Hello'
        sleep 1m
