name: 'Push'

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}-${{ vars.wfvar }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}

jobs:
  env-and-sleep:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.sha }}-${{ github.job }}-${{ vars.esjobvar }}
      cancel-in-progress: true
    steps:
      - run: |
          env
          sleep 90s

  hello-and-sleep:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ vars.hsjobvar }}
      cancel-in-progress: true
    steps:
      - run: |
          echo 'Hello'
          sleep 90s
